version: 2
updates:
  # Ignore all updates to the `tests` directory (old webpack 4 tests)
  - package-ecosystem: "npm"
    directory: "/tests"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "npm"
    directory: "/tests_webpack"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/examples"
    schedule:
      interval: "weekly"
